---
- name: restart ssh
  service: name=ssh state=restarted

- name: restart journald
  service: name=systemd-journald state=restarted

- name: Reload systemd daemons
  shell: systemctl daemon-reload
