---
- name: Add debmon repo
  apt_repository: repo='deb http://debmon.org/debmon debmon-jessie main'
                  state=present

- name: Add debmon key
  apt_key: data="{{lookup('file','debmon.gpg')}}" state=present

- name: Install icinga2
  apt: name={{item}} state=present update_cache=yes
  with_items:
  - icinga2
  - icinga2-ido-pgsql
  - icingaweb2
  - monitoring-plugins
  - php5-intl
  - php5-imagick
  - php5-pgsql

- name: Put icinga2 graphite config
  template:
    dest=/etc/icinga2/features-available/graphite.conf
    src=graphite.conf.j2
  notify: Restart icinga2

- name: Enable icinga2 modules
  command: icinga2 feature enable "{{item}}"
           creates="/etc/icinga2/features-enabled/{{item}}.conf"
  notify: Restart icinga2
  with_items:
  - command
  - graphite
  - ido-pgsql

- name: Add www-data to icinga groups
  user: name=www-data
        append=yes
        groups=icingaweb2
  notify: Restart apache

- name: Configure php timezone
  lineinfile: dest=/etc/php5/apache2/php.ini
              line="date.timezone = Europe/Berlin"
              insertafter=";date.timezone ="
  notify: Restart apache

- name: Stat config.ini
  stat: path=/etc/icingaweb2/config.ini

  register: icingaweb2_config

- name: Create setup token
  command: icingacli setup token create
           creates=/etc/icingaweb2/setup.token
  when: icingaweb2_config.stat.exists == False

- name: Ensure correct permissions for icingaweb2
  file: path=/etc/icingaweb2
        owner=www-data
        group=icingaweb2
        recurse=yes
        state=directory

- name: Ensure icings2 gets run
  service: name=icinga2
           state=started
           enabled=yes

- include: plugins.yml
- include: config.yml
